service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: "s3:ListBucket"
      Resource: "arn:aws:s3:::bucket-for-import-files"
    - Effect: Allow
      Action: "s3:*"
      Resource: "arn:aws:s3:::bucket-for-import-files/*"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: bucket-for-import-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
