service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  bucketName: bucket-for-import-files


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  environment:
    BUCKET: ${self:custom.bucketName}
    SQS_URL:
      Ref: SQSQueue
  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::${self:custom.bucketName}
    - Effect: Allow
      Action: s3:*
      Resource: arn:aws:s3:::${self:custom.bucketName}/*
    - Effect: Allow
      Action: sqs:*
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]


functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: import-products-from-file-queue

