service: import-service

frameworkVersion: '3'

plugins:
  - serverless-webpack

custom:
  bucketName: bucket-for-import-files


provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::${self:custom.bucketName}
    - Effect: Allow
      Action: s3:*
      Resource: arn:aws:s3:::${self:custom.bucketName}/*


functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          method: get
          path: /import
          cors: true
    environment:
      BUCKET: ${self:custom.bucketName}

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: bucket-for-import-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
    environment:
      BUCKET: ${self:custom.bucketName}
